/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.TaiKhoan;

import BUS.BCrypt;
import BUS.bus_TaiKhoan;
import DTO.dto_TaiKhoan;
import UI.DangNhap.UI_DangNhap;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class pnDoiMatKhau extends javax.swing.JPanel {

    /**
     * Creates new form pnDoiMatKhau
     */
    dto_TaiKhoan tk;
    public pnDoiMatKhau() {
        initComponents();
        giaoDienBanDau();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // HÀM SET GIAO DIỆN BAN ĐẦU
    public void giaoDienBanDau(){
        this.tk = new dto_TaiKhoan();
        tk = UI_DangNhap.layTaiKhoanDangNhap();
        
        lblTenNhanVien.setText("XIN CHÀO " + tk.getHoTen());
        txtMatKhauCu.setText("");
        txtMatKhauMoi.setText("");
        txtNhapLaiMatKhau.setText("");
    }
    
    
    // HÀM CẬP NHẬT MẬT KHẨU
    public void capNhatMatKhau(){
        
        dto_TaiKhoan tkMoi = layThongTinNhap();
        
        if(tkMoi != null){
            
            int kq = new bus_TaiKhoan().capNhatMatKhau(tk);
            
            if(kq > 0){
                
                JOptionPane.showMessageDialog(null, "Đã cập nhật mật khẩu");
                giaoDienBanDau();
            }
            else
                JOptionPane.showMessageDialog(null, "Lỗi");
        }
    }
    // HÀM LẤY THÔNG TIN NHÂP
    public dto_TaiKhoan layThongTinNhap(){
        
        String mkCu = txtMatKhauCu.getText();
        String mkMoi = txtMatKhauMoi.getText();
        String mkMoiNhapLai = txtNhapLaiMatKhau.getText();
        
        if(mkCu.isEmpty() || mkMoi.isEmpty() || mkMoiNhapLai.isEmpty()){
            JOptionPane.showMessageDialog(null, "Chưa điền đủ thông tin");
            return null;     
        }
        
        boolean ktMatKhauCu = BCrypt.checkpw(mkCu, this.tk.getMatKhau());
        
        if(ktMatKhauCu == false){
            JOptionPane.showMessageDialog(null, "Mật khẩu cũ không chính xác");
            return null;    
        }
        
        if(mkMoi.compareTo(mkMoiNhapLai) != 0){
            JOptionPane.showMessageDialog(null, "Mật khẩu xác nhận không chính xác");
            return null;    
        }
        
        boolean ktTrung = BCrypt.checkpw(mkMoi, this.tk.getMatKhau());
        
        if(ktTrung == true){
            JOptionPane.showMessageDialog(null, "Bạn đã nhập mật khẩu cũ");
            return null;    
        }
        
        dto_TaiKhoan tkMoi = new dto_TaiKhoan();
        tkMoi = this.tk;
        String hash = BCrypt.hashpw(mkMoi, BCrypt.gensalt(12));
        tkMoi.setMatKhau(hash);
        
        return tkMoi;
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMatKhauMoi = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        txtMatKhauCu = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txtNhapLaiMatKhau = new javax.swing.JPasswordField();
        lblTenNhanVien = new javax.swing.JLabel();
        lblCapNhat = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1350, 634));

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 0, 153));
        kGradientPanel1.setMinimumSize(new java.awt.Dimension(1350, 634));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(1350, 634));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/key.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ĐỔI MẬT KHẨU");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mật Khẩu Cũ");

        txtMatKhauMoi.setBackground(new java.awt.Color(239, 231, 231));
        txtMatKhauMoi.setText("jPasswordField1");
        txtMatKhauMoi.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Xác Nhận Mật Khẩu Mới");

        txtMatKhauCu.setBackground(new java.awt.Color(239, 231, 231));
        txtMatKhauCu.setText("jPasswordField1");
        txtMatKhauCu.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mật Khẩu Mới");

        txtNhapLaiMatKhau.setBackground(new java.awt.Color(239, 231, 231));
        txtNhapLaiMatKhau.setText("jPasswordField1");
        txtNhapLaiMatKhau.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));

        lblTenNhanVien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTenNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        lblTenNhanVien.setText("XIN CHÀO CHU MINH TÂN");

        lblCapNhat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        lblCapNhat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCapNhat.setText("CẬP NHẬT");
        lblCapNhat.setAutoscrolls(true);
        lblCapNhat.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        lblCapNhat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCapNhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCapNhatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(47, 47, 47)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNhapLaiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(lblCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 304, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblTenNhanVien))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(lblTenNhanVien)
                        .addGap(94, 94, 94)
                        .addComponent(jLabel2)
                        .addGap(95, 95, 95)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(txtMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNhapLaiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(60, 60, 60)
                        .addComponent(lblCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 111, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblCapNhatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCapNhatMouseClicked
        capNhatMatKhau();
    }//GEN-LAST:event_lblCapNhatMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lblCapNhat;
    private javax.swing.JLabel lblTenNhanVien;
    private javax.swing.JPasswordField txtMatKhauCu;
    private javax.swing.JPasswordField txtMatKhauMoi;
    private javax.swing.JPasswordField txtNhapLaiMatKhau;
    // End of variables declaration//GEN-END:variables
}
