package UI.LopHoc;

import BUS.bus_LopHoc;
import DTO.dto_ChuongTrinh;
import DTO.dto_LopHoc;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

public class FormCapNhatLop extends javax.swing.JDialog {

    /**
     * Creates new form FormCapNhatLop
     */
    
    private dto_LopHoc lopChon;
    
    public FormCapNhatLop() {
        initComponents();
    }
    
    public FormCapNhatLop(dto_LopHoc lopChon){
        initComponents();
        this.lopChon = new dto_LopHoc();
        this.lopChon = lopChon;
        
        setGiaoDienBanDau();
    }
    
    //DefaultComboBoxModel dfcbChuongTrinh;
    ArrayList<dto_ChuongTrinh> dsChuongTrinh;
    ArrayList<dto_LopHoc> dsLopHoc;

    // HÀM CẬP NHẬT THÔNG TIN
    public void capNhatLop() {

        dto_LopHoc lop = new dto_LopHoc();
        lop = layThongTinNhap();

        if (lop != null) {
            int rs = new bus_LopHoc().capNhatLop(lop);

            if (rs == 0) {
                JOptionPane.showMessageDialog(null, "Không thành công");
            } else {
                this.dispose();
                JOptionPane.showMessageDialog(null, "Cập Nhật Hoàn Tất");
                UI_LopHoc.reloadDuLieuLop();
            }
        }

    }
            
    
    // HÀM LẤY THÔNG TIN NHẬP & KIỂM TRA DỮ LIỆU & TRẢ VỀ ĐỐI TƯỢNG LỚP HỌC
    public dto_LopHoc layThongTinNhap(){
        
        dto_LopHoc lop = null;
        
        String tenLop = txtTenLop.getText();
        
        
        dto_ChuongTrinh ct = this.dsChuongTrinh.get(cbChuongTrinh.getSelectedIndex());
        
        if(tenLop.isEmpty()|| ct == null){
            JOptionPane.showMessageDialog(null, "Chưa Nhập Đủ Thông Tin");
            return null;
        }
        
        
        lop = new dto_LopHoc();
        lop.setMaLop(this.lopChon.getMaLop());
        lop.setMaCt(ct.getMaCt());
        lop.setTenLop(tenLop);
              
        return lop;
    }

    // HÀM SET GIAO DIỆN BAN ĐẦU
    public void setGiaoDienBanDau(){
        dsLopHoc = new ArrayList<dto_LopHoc>();
        dsLopHoc = UI_LopHoc.getDsLopHoc();
        
        dsChuongTrinh = new ArrayList<dto_ChuongTrinh>();
        dsChuongTrinh = new bus_LopHoc().layDsChuongTrinh();
        
        txtTenLop.setText(this.lopChon.getTenLop());
      
        cbChuongTrinh.removeAllItems();
        for(dto_ChuongTrinh ct: this.dsChuongTrinh){
            cbChuongTrinh.addItem(ct.getTenCt());
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCapNhatLop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTenLop = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbChuongTrinh = new javax.swing.JComboBox<>();
        btnXacNhan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cập Nhật Lớp");
        setMinimumSize(new java.awt.Dimension(500, 250));

        pnCapNhatLop.setBackground(new java.awt.Color(230, 245, 255));
        pnCapNhatLop.setMinimumSize(new java.awt.Dimension(500, 250));

        jLabel1.setText("Tên Lớp");

        txtTenLop.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtTenLop.setText("TOEIC 500 - K12");

        jLabel2.setText("Chương Trình");

        cbChuongTrinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnXacNhan.setBackground(new java.awt.Color(0, 102, 153));
        btnXacNhan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnXacNhan.setText("XÁC NHẬN");
        btnXacNhan.setContentAreaFilled(false);
        btnXacNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXacNhan.setFocusable(false);
        btnXacNhan.setOpaque(true);
        btnXacNhan.setPreferredSize(new java.awt.Dimension(209, 40));
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnCapNhatLopLayout = new javax.swing.GroupLayout(pnCapNhatLop);
        pnCapNhatLop.setLayout(pnCapNhatLopLayout);
        pnCapNhatLopLayout.setHorizontalGroup(
            pnCapNhatLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCapNhatLopLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pnCapNhatLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(pnCapNhatLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cbChuongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
            .addGroup(pnCapNhatLopLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnCapNhatLopLayout.setVerticalGroup(
            pnCapNhatLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCapNhatLopLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnCapNhatLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCapNhatLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbChuongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCapNhatLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCapNhatLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(516, 239));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed

        capNhatLop();
    }//GEN-LAST:event_btnXacNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCapNhatLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCapNhatLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCapNhatLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCapNhatLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCapNhatLop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JComboBox<String> cbChuongTrinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pnCapNhatLop;
    private javax.swing.JTextField txtTenLop;
    // End of variables declaration//GEN-END:variables
}
