package UI.LopHoc;

import BUS.bus_LopHoc;
import DTO.dto_ChuongTrinh;
import DTO.dto_LopHoc;
import UI.DangNhap.UI_DangNhap;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class FormThemLop extends javax.swing.JDialog {

    /**
     * Creates new form FormThemLop
     */
    public FormThemLop() {
        this.setModal(true);
        initComponents();
        setGiaoDienBanDau();
    }

    DefaultComboBoxModel dfcbChuongTrinh;
    ArrayList<dto_ChuongTrinh> dsChuongTrinh;
    ArrayList<dto_LopHoc> dsLopHoc;

    // HÀM THÊM LỚP HỌC VÀO DB
    public void themLopHoc() {

        dto_LopHoc lop = new dto_LopHoc();
        lop = layThongTinNhap();

        if (lop != null) {
            int rs = new bus_LopHoc().themLopHoc(lop);

            if (rs == 0) {
                JOptionPane.showMessageDialog(null, "Thêm Không Thành Công");
            } else {
                this.dispose();
                JOptionPane.showMessageDialog(null, "Thêm Hoàn Tất");
                UI_LopHoc.reloadDuLieuLop();
            }
        }

    }

    // HÀM LẤY THÔNG TIN NHẬP & KIỂM TRA DỮ LIỆU & TRẢ VỀ ĐỐI TƯỢNG LỚP HỌC
    public dto_LopHoc layThongTinNhap() {

        dto_LopHoc lop = null;

        String tenLop = txtTenLop.getText();

        dto_ChuongTrinh ct = this.dsChuongTrinh.get(cbChuongTrinh.getSelectedIndex());
        
        if (tenLop.isEmpty() || ct == null) {
            JOptionPane.showMessageDialog(null, "Chưa Nhập Đủ Thông Tin");
            return null;
        }

        int soBuoi = 0;

        lop = new dto_LopHoc();
        lop.setMaNv(UI_DangNhap.layMaNguoiDung());
        lop.setMaCt(ct.getMaCt());
        lop.setTenLop(tenLop);
        lop.setSoBuoi(soBuoi);
        return lop;
    }

    // HÀM SET GIAO DIỆN BAN ĐẦU
    public void setGiaoDienBanDau() {
        dsLopHoc = new ArrayList<dto_LopHoc>();
        dsLopHoc = UI_LopHoc.getDsLopHoc();

        dsChuongTrinh = new ArrayList<dto_ChuongTrinh>();
        dsChuongTrinh = new bus_LopHoc().layDsChuongTrinh();

        dfcbChuongTrinh = new DefaultComboBoxModel();
        dfcbChuongTrinh.addAll(dsChuongTrinh);
        txtTenLop.setText("");

        cbChuongTrinh.setModel(dfcbChuongTrinh);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnThemLop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTenLop = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbChuongTrinh = new javax.swing.JComboBox<>();
        btnXacNhan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tạo Lớp Học Mới");
        setBackground(new java.awt.Color(230, 245, 255));
        setMinimumSize(new java.awt.Dimension(500, 250));

        pnThemLop.setBackground(new java.awt.Color(230, 245, 255));
        pnThemLop.setMinimumSize(new java.awt.Dimension(500, 250));
        pnThemLop.setPreferredSize(new java.awt.Dimension(500, 250));

        jLabel1.setText("Tên Lớp");

        txtTenLop.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtTenLop.setText("TOEIC 500 - K12");

        jLabel2.setText("Chương Trình");

        cbChuongTrinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnXacNhan.setBackground(new java.awt.Color(0, 102, 153));
        btnXacNhan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnXacNhan.setText("XÁC NHẬN");
        btnXacNhan.setContentAreaFilled(false);
        btnXacNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXacNhan.setFocusable(false);
        btnXacNhan.setOpaque(true);
        btnXacNhan.setPreferredSize(new java.awt.Dimension(209, 40));
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnThemLopLayout = new javax.swing.GroupLayout(pnThemLop);
        pnThemLop.setLayout(pnThemLopLayout);
        pnThemLopLayout.setHorizontalGroup(
            pnThemLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemLopLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pnThemLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(pnThemLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cbChuongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
            .addGroup(pnThemLopLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnThemLopLayout.setVerticalGroup(
            pnThemLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemLopLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnThemLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnThemLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbChuongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnThemLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnThemLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(516, 197));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed

        themLopHoc();
    }//GEN-LAST:event_btnXacNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormThemLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormThemLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormThemLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormThemLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormThemLop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JComboBox<String> cbChuongTrinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pnThemLop;
    private javax.swing.JTextField txtTenLop;
    // End of variables declaration//GEN-END:variables
}
