package UI.LopHoc;

import BUS.bus_LopHoc;
import DTO.dto_Lich;
import DTO.dto_LopHoc;
import java.util.ArrayList;
import java.util.Date;

public class pnLocNgay extends javax.swing.JPanel {

    /**
     * Creates new form pnLocNgay
     */
    private Date ngayChon;
    private ArrayList<dto_LopHoc> dsLop;
    private ArrayList<dto_LopHoc> dsLopPhuHop;

    public pnLocNgay() {
        initComponents();
        reloadDuLieu();
    }

    // HÀM SET DỮ LIỆU
    public void reloadDuLieu() {

        this.dsLop = new ArrayList<dto_LopHoc>();
        this.dsLop = new bus_LopHoc().layDsLop(true);

        int size = this.dsLop.size();
        for (int i = 0; i < size; i++) {

            this.dsLop.get(i).setDsLich(new bus_LopHoc().layDsLichTheoLop(this.dsLop.get(i).getMaLop()));
        }

        this.dsLop = new bus_LopHoc().layChuongTrinh(dsLop);
        dcNgay.setDate(null);
    }

    // HÀM HIỂN THỊ LỚP ĐÃ LỌC
    public void hienThiLopDaLoc() {
        ngayChon = new Date();
        ngayChon = dcNgay.getDate();

        if (ngayChon != null) {
            layDanhSachPhuHop();
            UI_LopHoc.reloadTableLop(dsLopPhuHop);
        } else {
            UI_LopHoc.reloadTableLop(dsLop);
        }
    }

    public void stateChanged(javax.swing.event.ChangeEvent e) {
        System.out.println("h");

    }

    // HÀM KIỂM TRA DANH SÁCH LỚP NHỮNG LỚP CÓ THỨ ĐÚNG VỚI YÊU CẦU
    public void layDanhSachPhuHop() {

        dsLopPhuHop = new ArrayList<dto_LopHoc>();

        int size = this.dsLop.size();
        for (int i = 0; i < size; i++) {

            this.dsLop.get(i).setDsLich(new bus_LopHoc().layDsLichTheoLop(this.dsLop.get(i).getMaLop()));
        }

        boolean timDuoc;

        // duyệt từng lớp đang có
        for (dto_LopHoc lop : dsLop) {

            timDuoc = false;

            //lấy ds những ngày học của lớp đó
            ArrayList<dto_Lich> dsLich = lop.getDsLich();

            //kiểm tra từng ngày trong lớp xem có thứ trùng với thứ đã check không
            for (dto_Lich lich : dsLich) {
                int namLich = lich.getTgBd().getYear();
                int thangLich = lich.getTgBd().getMonth();
                int ngayLich = lich.getTgBd().getDate();

                if (ngayChon.getYear() == namLich && ngayChon.getMonth() == thangLich && ngayChon.getDate() == ngayLich) {
                    timDuoc = true;
                    dsLopPhuHop.add(lop);
                    break;
                }
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dcNgay = new com.toedter.calendar.JDateChooser();
        btnXoaNgay = new javax.swing.JButton();

        setBackground(new java.awt.Color(230, 245, 255));
        setMinimumSize(new java.awt.Dimension(347, 30));
        setPreferredSize(new java.awt.Dimension(347, 30));

        dcNgay.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dcNgayPropertyChange(evt);
            }
        });

        btnXoaNgay.setBackground(new java.awt.Color(0, 102, 153));
        btnXoaNgay.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaNgay.setText("Đặt Lại");
        btnXoaNgay.setBorderPainted(false);
        btnXoaNgay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoaNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNgayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dcNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnXoaNgay)
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dcNgay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnXoaNgay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNgayActionPerformed
        dcNgay.setDate(null);
    }//GEN-LAST:event_btnXoaNgayActionPerformed

    private void dcNgayPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dcNgayPropertyChange
        hienThiLopDaLoc();
    }//GEN-LAST:event_dcNgayPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXoaNgay;
    private com.toedter.calendar.JDateChooser dcNgay;
    // End of variables declaration//GEN-END:variables
}
